config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :projects
  root 'projects#index'

end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
  validates :planName,
    presence: {message: "内容がないよう"},
    length: {minimum: 3, message: "3文字以上で頼むわ"}
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :projects
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_action :authenticate_user!,:set_project, only: [:show, :edit, :update, :destroy]

  def index
    @projects = Project.all
  end

  def show
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    if
      @project.user_id = current_user.id
      @project.save
      redirect_to projects_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @project.update(project_params)
      redirect_to project_path
    else
      render 'edit'
    end
  end

  def destroy
    @project.destroy
    redirect_to projects_path
  end

  private

  def project_params
    params[:project].permit(:planName, :description, :wantPersons, :projectStatus)
  end

  def set_project
    @project = Project.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Funservice</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
<%= image_tag "logo.png" %>
  <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
<% end %>
<p class="navbar-text pull-right">
<% if user_signed_in? %>
    Logged in as <strong><%= current_user.email %></strong>.
    <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
    <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
    <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
    <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>
</div>

<div class="container">
<%= yield %>

<%= link_to "Home", projects_path %>
 </div>

</body>
</html>

app/views/projects/_form.html.erb
<%= form_for @project do |f| %>

<p>
  <%= f.label :planName, "プロジェクト名"%><br>
  <%= f.text_field :planName %>
  <% if @project.errors.any? %>
  <%= @project.errors.messages[:planName][0] %>
  <% end %>
</p>

<p>
  <%= f.label :description, "内容" %><br>
  <%= f.text_area :description %>
</p>

<p>
  <%= f.label :wantPersons, "募集人数" %><br>
  <%= f.number_field :wantPersons %>
</p>

<p>
  <%= f.label :projectStatus, "進捗状況" %><br>
  <%= f.text_field :projectStatus %>
</p>

<p>
  <%= f.submit %>
</p>

<% end %>

app/views/projects/edit.html.erb
<h1>Edit</h1>

<%= render 'form' %>

app/views/projects/index.html.erb
<h1>Project</h1>



<table class="table">
  <tr>
    <th>募集中の企画</th>
    <th>募集人数</th>
    <th>主催者ID</th>
    <th></th>
    <th></th>
  </tr>


  <% @projects.each do |project| %>
  <tr>
    <td><%= link_to project.planName, project_path(project.id) %></td>
    <td><%= project.wantPersons %></td>
    <td><%= project.user_id %></td>
    <td><%= link_to "[編集]", edit_project_path(project.id) %></td>
    <td><%= link_to "[削除]", project_path(project.id), method: :delete, data: { confirm: "えっ、消すけどいいの？" }%></td>
  </tr>
  <% end %>
</table>

<p><%= link_to "Add New Project", new_project_path %></p>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form' %>

app/views/projects/show.html.erb
<h1><%= @project.planName %></h1>
<table>
  <tr>
    <th>内容</th>
    <td><%= @project.description %></td>
  </tr>
  <tr>
    <th>募集人数</th>
    <td><%= @project.wantPersons %>人</td>
  </tr>
  <tr>
    <th>進捗状況</th>
    <td><%= @project.projectStatus %></td>
  </tr>
</table>